name: flutter_ai_shop_test
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  retrofit: ^4.8.0
  get_it: ^8.3.0
  go_router: ^16.3.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_hooks: ^0.21.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.1
  freezed: ^3.2.3
  retrofit_generator: ^10.0.6

flutter:
  uses-material-design: true
  assets:
    - .env
